name: Build Debug APK

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Change to V2rayNG directory and grant permission
        run: |
          cd V2rayNG
          chmod +x gradlew

      - name: Build with Gradle
        run: |
          cd V2rayNG
          ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: V2rayNG/app/build/outputs/apk/debug/app-debug.apk
